#!/usr/bin/env bash
# Compatibility entrypoint: Main KPI is the canonical source; KPI standalone is
# generated by scripts/sync-kpi-source.js with its read-only navigation patch.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [ "${1:-}" = "--check" ]; then
  exec node "$ROOT/scripts/sync-kpi-source.js" --check
fi

if [ "$#" -gt 0 ]; then
  echo "ERROR: unsupported argument: $1" >&2
  echo "Usage: bash scripts/sync-kpi-app.sh [--check]" >&2
  exit 1
fi

exec node "$ROOT/scripts/sync-kpi-source.js"
